# Generated by Django 5.2.1 on 2025-05-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
